# Export langs as defined in rails
window.langs =
  fr: "Français"
  en: "Anglais"
  de: "Allemand"
  eu: "Basque"
  ct: "Catalan"
  cn: "Chinois"
  ko: "Coréen"
  da: "Danois"
  es: "Espagnol"
  fi: "Finnois"
  el: "Grec"
  it: "Italien"
  ja: "Japonais"
  nl: "Néerlandais"
  no: "Norvégien"
  pl: "Polonais"
  pt: "Portugais"
  ru: "Russe"
  sv: "Suédois"
  xx: "!? hmmm ?!"

